#!/bin/sh -l
set -eu

echo Converting tabs to spaces
find ./ -iname '*.sql' -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;

echo Remove trailing whitespace
find ./ -iname '*.yml' -type f -exec bash -c 'sed -i 's/[ \t]*$//' "$0" | sponge "$0"' {} \;
